//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 01.09.2023 3:04:41
namespace DaJet
{
    /// <summary>
    /// There are no comments for EntityObjectSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EntityObjectSingle")]
    public partial class EntityObjectSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<EntityObject>
    {
        /// <summary>
        /// Initialize a new EntityObjectSingle object.
        /// </summary>
        public EntityObjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new EntityObjectSingle object.
        /// </summary>
        public EntityObjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new EntityObjectSingle object.
        /// </summary>
        public EntityObjectSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<EntityObject> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for EntityObject in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Identity
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Identity")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("EntityObject")]
    public abstract partial class EntityObject : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Identity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Identity")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Identity is required.")]
        public virtual global::System.Guid Identity
        {
            get
            {
                return this._Identity;
            }
            set
            {
                this.OnIdentityChanging(value);
                this._Identity = value;
                this.OnIdentityChanged();
                this.OnPropertyChanged("Identity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _Identity;
        partial void OnIdentityChanging(global::System.Guid value);
        partial void OnIdentityChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DaJet.EntityObject as global::DaJet.EntityObjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::DaJet.EntityObjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.EntityObject> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::DaJet.EntityObjectSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::DaJet.EntityObject as global::DaJet.EntityObjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="identity">The value of identity</param>
        public static global::DaJet.EntityObjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.EntityObject> _source,
            global::System.Guid identity)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Identity", identity }
            };
            return new global::DaJet.EntityObjectSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace DaJet.Model
{
    /// <summary>
    /// There are no comments for PipelineBlockRecordSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PipelineBlockRecordSingle")]
    public partial class PipelineBlockRecordSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PipelineBlockRecord>
    {
        /// <summary>
        /// Initialize a new PipelineBlockRecordSingle object.
        /// </summary>
        public PipelineBlockRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PipelineBlockRecordSingle object.
        /// </summary>
        public PipelineBlockRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PipelineBlockRecordSingle object.
        /// </summary>
        public PipelineBlockRecordSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PipelineBlockRecord> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PipelineBlockRecord in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Identity
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Identity")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PipelineBlockRecord")]
    public partial class PipelineBlockRecord : global::DaJet.EntityObject
    {
        /// <summary>
        /// Create a new PipelineBlockRecord object.
        /// </summary>
        /// <param name="identity">Initial value of Identity.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PipelineBlockRecord CreatePipelineBlockRecord(global::System.Guid identity)
        {
            PipelineBlockRecord pipelineBlockRecord = new PipelineBlockRecord();
            pipelineBlockRecord.Identity = identity;
            return pipelineBlockRecord;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for PipelineRecordSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PipelineRecordSingle")]
    public partial class PipelineRecordSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PipelineRecord>
    {
        /// <summary>
        /// Initialize a new PipelineRecordSingle object.
        /// </summary>
        public PipelineRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PipelineRecordSingle object.
        /// </summary>
        public PipelineRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PipelineRecordSingle object.
        /// </summary>
        public PipelineRecordSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PipelineRecord> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PipelineRecord in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Identity
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Identity")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PipelineRecord")]
    public partial class PipelineRecord : global::DaJet.EntityObject
    {
        /// <summary>
        /// Create a new PipelineRecord object.
        /// </summary>
        /// <param name="identity">Initial value of Identity.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PipelineRecord CreatePipelineRecord(global::System.Guid identity)
        {
            PipelineRecord pipelineRecord = new PipelineRecord();
            pipelineRecord.Identity = identity;
            return pipelineRecord;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for TreeNodeRecordSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TreeNodeRecordSingle")]
    public partial class TreeNodeRecordSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<TreeNodeRecord>
    {
        /// <summary>
        /// Initialize a new TreeNodeRecordSingle object.
        /// </summary>
        public TreeNodeRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TreeNodeRecordSingle object.
        /// </summary>
        public TreeNodeRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TreeNodeRecordSingle object.
        /// </summary>
        public TreeNodeRecordSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<TreeNodeRecord> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Value")]
        public virtual global::DaJet.EntityObjectSingle Value
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Value == null))
                {
                    this._Value = new global::DaJet.EntityObjectSingle(this.Context, GetPath("Value"));
                }
                return this._Value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DaJet.EntityObjectSingle _Value;
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Parent")]
        public virtual global::DaJet.Model.TreeNodeRecordSingle Parent
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Parent == null))
                {
                    this._Parent = new global::DaJet.Model.TreeNodeRecordSingle(this.Context, GetPath("Parent"));
                }
                return this._Parent;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DaJet.Model.TreeNodeRecordSingle _Parent;
    }
    /// <summary>
    /// There are no comments for TreeNodeRecord in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Identity
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Identity")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("TreeNodeRecord")]
    public partial class TreeNodeRecord : global::DaJet.EntityObject
    {
        /// <summary>
        /// Create a new TreeNodeRecord object.
        /// </summary>
        /// <param name="identity">Initial value of Identity.</param>
        /// <param name="isFolder">Initial value of IsFolder.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static TreeNodeRecord CreateTreeNodeRecord(global::System.Guid identity, bool isFolder)
        {
            TreeNodeRecord treeNodeRecord = new TreeNodeRecord();
            treeNodeRecord.Identity = identity;
            treeNodeRecord.IsFolder = isFolder;
            return treeNodeRecord;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property IsFolder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsFolder")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IsFolder is required.")]
        public virtual bool IsFolder
        {
            get
            {
                return this._IsFolder;
            }
            set
            {
                this.OnIsFolderChanging(value);
                this._IsFolder = value;
                this.OnIsFolderChanged();
                this.OnPropertyChanged("IsFolder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _IsFolder;
        partial void OnIsFolderChanging(bool value);
        partial void OnIsFolderChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Value")]
        public virtual global::DaJet.EntityObject Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
                this.OnPropertyChanged("Value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DaJet.EntityObject _Value;
        partial void OnValueChanging(global::DaJet.EntityObject value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Parent")]
        public virtual global::DaJet.Model.TreeNodeRecord Parent
        {
            get
            {
                return this._Parent;
            }
            set
            {
                this.OnParentChanging(value);
                this._Parent = value;
                this.OnParentChanged();
                this.OnPropertyChanged("Parent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::DaJet.Model.TreeNodeRecord _Parent;
        partial void OnParentChanging(global::DaJet.Model.TreeNodeRecord value);
        partial void OnParentChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DaJet.Model.PipelineBlockRecord as global::DaJet.Model.PipelineBlockRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::DaJet.Model.PipelineBlockRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.PipelineBlockRecord> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::DaJet.Model.PipelineBlockRecordSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::DaJet.Model.PipelineBlockRecord as global::DaJet.Model.PipelineBlockRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="identity">The value of identity</param>
        public static global::DaJet.Model.PipelineBlockRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.PipelineBlockRecord> _source,
            global::System.Guid identity)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Identity", identity }
            };
            return new global::DaJet.Model.PipelineBlockRecordSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::DaJet.EntityObject to its derived type global::DaJet.Model.PipelineBlockRecord
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::DaJet.Model.PipelineBlockRecordSingle CastToPipelineBlockRecord(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::DaJet.EntityObject> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::DaJet.Model.PipelineBlockRecord> query = _source.CastTo<global::DaJet.Model.PipelineBlockRecord>();
            return new global::DaJet.Model.PipelineBlockRecordSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::DaJet.Model.PipelineRecord as global::DaJet.Model.PipelineRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::DaJet.Model.PipelineRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.PipelineRecord> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::DaJet.Model.PipelineRecordSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::DaJet.Model.PipelineRecord as global::DaJet.Model.PipelineRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="identity">The value of identity</param>
        public static global::DaJet.Model.PipelineRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.PipelineRecord> _source,
            global::System.Guid identity)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Identity", identity }
            };
            return new global::DaJet.Model.PipelineRecordSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::DaJet.EntityObject to its derived type global::DaJet.Model.PipelineRecord
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::DaJet.Model.PipelineRecordSingle CastToPipelineRecord(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::DaJet.EntityObject> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::DaJet.Model.PipelineRecord> query = _source.CastTo<global::DaJet.Model.PipelineRecord>();
            return new global::DaJet.Model.PipelineRecordSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::DaJet.Model.TreeNodeRecord as global::DaJet.Model.TreeNodeRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::DaJet.Model.TreeNodeRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.TreeNodeRecord> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::DaJet.Model.TreeNodeRecordSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::DaJet.Model.TreeNodeRecord as global::DaJet.Model.TreeNodeRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="identity">The value of identity</param>
        public static global::DaJet.Model.TreeNodeRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.TreeNodeRecord> _source,
            global::System.Guid identity)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Identity", identity }
            };
            return new global::DaJet.Model.TreeNodeRecordSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::DaJet.EntityObject to its derived type global::DaJet.Model.TreeNodeRecord
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::DaJet.Model.TreeNodeRecordSingle CastToTreeNodeRecord(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::DaJet.EntityObject> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::DaJet.Model.TreeNodeRecord> query = _source.CastTo<global::DaJet.Model.TreeNodeRecord>();
            return new global::DaJet.Model.TreeNodeRecordSingle(_source.Context, query.GetPath(null));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "DaJet.Model", "DaJet.Model");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "DaJet", "DaJet");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("DaJet.Model", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("DaJet.Model.", originalNameAttribute.OriginalName);
                }
                return string.Concat("DaJet.Model.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DaJet", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("DaJet.", originalNameAttribute.OriginalName);
                }
                return string.Concat("DaJet.", clientType.Name);
            }
            if (originalNameAttribute != null)
            {
                return clientType.Namespace + "." + originalNameAttribute.OriginalName;
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for PipelineBlockRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PipelineBlockRecord")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.PipelineBlockRecord> PipelineBlockRecord
        {
            get
            {
                if ((this._PipelineBlockRecord == null))
                {
                    this._PipelineBlockRecord = base.CreateQuery<global::DaJet.Model.PipelineBlockRecord>("PipelineBlockRecord");
                }
                return this._PipelineBlockRecord;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.PipelineBlockRecord> _PipelineBlockRecord;
        /// <summary>
        /// There are no comments for PipelineRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PipelineRecord")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.PipelineRecord> PipelineRecord
        {
            get
            {
                if ((this._PipelineRecord == null))
                {
                    this._PipelineRecord = base.CreateQuery<global::DaJet.Model.PipelineRecord>("PipelineRecord");
                }
                return this._PipelineRecord;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.PipelineRecord> _PipelineRecord;
        /// <summary>
        /// There are no comments for TreeNodeRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TreeNodeRecord")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.TreeNodeRecord> TreeNodeRecord
        {
            get
            {
                if ((this._TreeNodeRecord == null))
                {
                    this._TreeNodeRecord = base.CreateQuery<global::DaJet.Model.TreeNodeRecord>("TreeNodeRecord");
                }
                return this._TreeNodeRecord;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DaJet.Model.TreeNodeRecord> _TreeNodeRecord;
        /// <summary>
        /// There are no comments for PipelineBlockRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToPipelineBlockRecord(global::DaJet.Model.PipelineBlockRecord pipelineBlockRecord)
        {
            base.AddObject("PipelineBlockRecord", pipelineBlockRecord);
        }
        /// <summary>
        /// There are no comments for PipelineRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToPipelineRecord(global::DaJet.Model.PipelineRecord pipelineRecord)
        {
            base.AddObject("PipelineRecord", pipelineRecord);
        }
        /// <summary>
        /// There are no comments for TreeNodeRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToTreeNodeRecord(global::DaJet.Model.TreeNodeRecord treeNodeRecord)
        {
            base.AddObject("TreeNodeRecord", treeNodeRecord);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"ODataSourceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
